#!/usr/bin/env python3
"""
Tree Merger Script

This script merges input gene trees with consensus trees generated by PAUP.
It creates a combined tree file containing:
1. All original gene trees from the input file
2. Consensus trees (strict, majority, greedy) with descriptive comments

Usage:
    python merge_trees.py -i input_trees.tre -o output_prefix

The script expects the following files to exist:
    - input_trees.tre (original gene trees)
    - output_prefix.strict.tree (strict consensus)  
    - output_prefix.majority.tree (majority rule consensus)
    - output_prefix.greedy.tree (greedy consensus)

Output:
    - output_prefix.merged.tree (combined file)
"""

import argparse
import os
import sys

def read_trees_from_file(filename):
    """Read trees from a file, returning non-empty lines."""
    if not os.path.exists(filename):
        return []
    
    trees = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                trees.append(line)
    return trees

def merge_trees(input_file, output_prefix):
    """
    Merge input gene trees with consensus trees.
    
    Args:
        input_file: Path to input gene trees file
        output_prefix: Prefix for output files
        
    Returns:
        Path to merged tree file
    """
    
    merged_file = f"{output_prefix}.merged.tree"
    
    # Define consensus tree files
    strict_file = f"{output_prefix}.strict.tree"
    majority_file = f"{output_prefix}.majority.tree"  
    greedy_file = f"{output_prefix}.greedy.tree"
    
    # Check if input file exists
    if not os.path.exists(input_file):
        print(f"Error: Input file {input_file} not found")
        return None
    
    # Read all trees
    input_trees = read_trees_from_file(input_file)
    strict_trees = read_trees_from_file(strict_file)
    majority_trees = read_trees_from_file(majority_file)
    greedy_trees = read_trees_from_file(greedy_file)
    
    # Create merged file
    with open(merged_file, 'w') as merged:
        # Write header comment
        merged.write("# Merged tree file containing input gene trees and consensus trees\n")
        merged.write(f"# Generated from: {input_file}\n")
        merged.write(f"# Total input trees: {len(input_trees)}\n\n")
        
        # Write input gene trees
        merged.write("# Input gene trees\n")
        for i, tree in enumerate(input_trees, 1):
            merged.write(f"{tree}\n")
        
        # Add consensus trees section
        merged.write(f"\n# Consensus trees\n")
        
        # Add strict consensus
        if strict_trees:
            merged.write("# Strict consensus tree\n")
            for tree in strict_trees:
                merged.write(f"{tree}\n")
        else:
            merged.write("# Strict consensus tree: not found\n")
            
        # Add majority rule consensus
        if majority_trees:
            merged.write("# Majority rule consensus tree\n")
            for tree in majority_trees:
                merged.write(f"{tree}\n")
        else:
            merged.write("# Majority rule consensus tree: not found\n")
            
        # Add greedy consensus
        if greedy_trees:
            merged.write("# Greedy consensus tree (le50)\n")
            for tree in greedy_trees:
                merged.write(f"{tree}\n")
        else:
            merged.write("# Greedy consensus tree: not found\n")
    
    return merged_file

def main():
    parser = argparse.ArgumentParser(
        description="Merge input gene trees with consensus trees from PAUP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument('-i', '--input', required=True,
                       help='Input gene trees file')
    parser.add_argument('-o', '--output', required=True,
                       help='Output prefix (same as used for PAUP consensus)')
    
    args = parser.parse_args()
    
    # Merge the trees
    merged_file = merge_trees(args.input, args.output)
    
    if merged_file:
        print(f"Successfully created merged tree file: {merged_file}")
        
        # Print summary
        with open(merged_file, 'r') as f:
            lines = f.readlines()
            tree_lines = [l for l in lines if l.strip() and not l.startswith('#')]
            comment_lines = [l for l in lines if l.strip().startswith('#')]
            
        print(f"Total trees in merged file: {len(tree_lines)}")
        print(f"Comment lines: {len(comment_lines)}")
    else:
        print("Failed to create merged tree file")
        sys.exit(1)

if __name__ == "__main__":
    main()
